![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [7]:
import numpy as np

my_array = np.arange(10)
print(my_array)

print(my_array[::-2])

reverse = np.flip(my_array)
print(reverse)

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]
[9 8 7 6 5 4 3 2 1 0]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [3]:

reverse = np.flip(my_array[-3:-1])
print(reverse)

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [8]:
print(my_array[-8 ::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [11]:
my_matrix = np.arange(1, 21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [13]:
my_matrix[::2, ::2]
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [14]:
print(my_matrix[:-1:, :: -1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [15]:
x = np.zeros( 10)
print(x)

print(x.itemsize)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
8


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [16]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [17]:
x = np.random.randint(1, 100, size = (10,10))
print(x)
print(x.min())
print(x.max())

[[24 21 54 27 53 88 59 50 16 10]
 [57 82 75 87 61 98 68 22  4 57]
 [30 79 78 53 89 95 74 38  5 42]
 [77 74 61 46 24  4 53 57 71 44]
 [24 17 98 48 20 39 92  8 52 20]
 [96 39 54 85 88 65 54 54 73 36]
 [41 25 34 31 16 64 84 29 50 28]
 [ 8 95 44 28 77 23 57  4 90 30]
 [15 93 81  1 58 40 77 52  9 57]
 [40  6 62 12 14 10  6 69 17 71]]
1
98


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [19]:
x=np.random.random(30)
print(x)
m=x.mean()
print(m)

[0.36690367 0.48644485 0.4803838  0.1949937  0.10410772 0.89419772
 0.68711074 0.69143402 0.34360165 0.58605304 0.96204071 0.61244127
 0.61255434 0.51162148 0.19981277 0.90070498 0.16614195 0.18583111
 0.54932305 0.10001404 0.75994332 0.46357992 0.5436221  0.58085973
 0.76774679 0.38995568 0.68880221 0.31488746 0.72577963 0.10954941]
0.4993480943102694


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [20]:
x = np.ones((10,10))
x[1:-1:, 1:-1:] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [36]:
x = np.ones((8,8))

x[1::2, 1::2] = 0
x[::2, ::2] = 0
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [37]:
x = np.zeros((8,8))
np.tile(x,1,[1::2, 1::2] = 1)
print(x)


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


## Ejercicio 9
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [38]:
x = np.random.randint(1, 20, (5,5))
print(x)
x = (x-np.mean(x))/np.std(x)
print(x)


[[18 14  8  2 16]
 [11 18 15 13 16]
 [ 6 10 10 15 19]
 [15  6  7  7  4]
 [11  3  2  8  9]]
[[ 1.46893876  0.68341001 -0.49488311 -1.67317623  1.07617438]
 [ 0.09426345  1.46893876  0.8797922   0.48702782  1.07617438]
 [-0.88764748 -0.10211874 -0.10211874  0.8797922   1.66532094]
 [ 0.8797922  -0.88764748 -0.6912653  -0.6912653  -1.28041186]
 [ 0.09426345 -1.47679404 -1.67317623 -0.49488311 -0.29850092]]


## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [39]:
x =  np.arange(11)
print(x)

y = x.copy()
y[(y>3)&(y<9)] = -1
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -1 -1 -1 -1 -1  9 10]


In [40]:
x =  np.arange(11)
print(x)

y = x.copy()
y[(y>3)&(y<9)] *= -1
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.