![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [10]:
import numpy as np
np.__version__

'1.21.6'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [12]:
my_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

## Ejercicio 4
Extrae todos los impares de `my_array`

In [13]:
pairs = my_array % 2 == 0
print(odds)
my_array [odds]

[ True False  True False  True False  True False  True False]


array([0, 2, 4, 6, 8])

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [18]:
three = my_array % 3 == 0
mynewarray = my_array.copy()
print(mynewarray)
mynewarray [odds] = -1
my_array[three] = -2
print(mynewarray)


[-2  1  2 -2  4  5 -2  7  8 -2]
[-2 -1  2 -2  4 -1 -2 -1  8 -2]
[-2  1  2 -2  4  5 -2  7  8 -2]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [17]:
odds = my_array %2 != 0
mynewarray = my_array.copy()
np.where(odds, -1,mynewarray)

array([-2, -1,  2, -2,  4, -1, -2, -1,  8, -2])

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [23]:
my_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(my_array.ndim)
print(my_array.shape)

my_array.reshape(2,5)

1
(10,)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [24]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [33]:
print (a)
print (b)
np.concatenate((a, b), axis = 0)

np.vstack((a, b))


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [34]:
print (a)
print (b)
np.concatenate((a, b), axis = 1)



[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [41]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b, assume_unique=False, return_indices=False)

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [42]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', '

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [48]:
my_array = np.arange(10)

my_array = my_array * 10

print(my_array)
print(my_array[0])
print(my_array[-1])
print(my_array[1:-2])

[ 0 10 20 30 40 50 60 70 80 90]
0
90
[10 20 30 40 50 60 70]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [54]:
my_matrix = np.array([[1,2,3], [2,2,3], [22,2,3] ])
my_matrix_auto = np.arange(9).reshape(3, 3)
my_matrix_auto2 = np.array([np.arange(3), np.arange(3), np.arange(3)])
print(my_matrix)
print(my_matrix_auto)
print(my_matrix_auto2)

[[ 1  2  3]
 [ 2  2  3]
 [22  2  3]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [56]:
my_matrix = np.arange(1,50, 3)
print(my_matrix)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [58]:
my_matrix = np.arange(4,1, -1/4)
print(my_matrix)

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png"

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [63]:
n = np.arange(4).reshape(4, 1)
print(n)

[[0]
 [1]
 [2]
 [3]]


## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [66]:
a = np.random.randint(10, 20, size = (120, 200, 4))

print(a)


ModuleNotFoundError: No module named 'imshow'

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?